name: sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run a multi-line script
        run: |
          while read line
          do
            echo $line;
            target=`echo $line |awk -F "/" '{print "masonmei/"$2"-"$3}'`
            docker pull $line
            docker tag $line $target
            docker push $target
          done < list
